name             'rentmania-backup'
maintainer       'b43'
maintainer_email 'perminovx@gmail.com'
license          'All rights reserved'
description      'Installs/Configures rentmania-backup'
long_description 'Installs/Configures rentmania-backup'
version          '0.1.6'
